### PR TITLE
Fix linker error upon following `README`’s Carthage instructions

### LINKED ISSUE #1183: App crash and dyld error message (AblyDeltaCodec cannot be loaded, image not found) when using XCFrameworks on macOS app.
A customer has reported that they’re getting a dyld error (AblyDeltaCodec cannot be loaded, image not found.) when attempting to use XCFrameworks instead of Carthage, whilst attempting to follow the instructions in

https://github.com/ably/ably-cocoa to build their macOS app.

The application runs fine from Xcode but upon installing the app on the test machine, the app crashes with dyld error message because AblyDeltaCodec cannot be loaded, image not found.

Steps followed prior to the error & crash were:

1-Changed Carthage update to include --use-xcframeworks
2-Removed the old framework references from the project
3-Dragged the three XCFrameworks from the Carthage build folder into the project
4-Confirmed that all three are in the Frameworks, Libraries and Embedded Content list on the General tab and that they have Do Not Embed selected
5-Confirmed all three are in the Link Binary with Libraries list in Build Phases

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1256) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
Resolves #1183. See commit messages for more details.

### CODE REVIEW

**Comment by maratal** [comment]
>These instructions were added in https://github.com/ably/ably-cocoa/commit/9a1e84cb10aace173bd43348b23ce75fdecf2f98, as part of the PR for adding
Swift Package Manager support

I bet it should be another commit hash here.

>This is the issue described by https://github.com/ably/ably-cocoa/pull/1599, which was resolved in https://github.com/ably/ably-cocoa/commit/9a1e84cb10aace173bd43348b23ce75fdecf2f98
by no longer embedding the dependency frameworks inside Ably.framework.

Not sure if "Emit retry attempt in state changes" has anything related to embedding frameworks.

**Comment by lawrence-forooghian** [comment]
Sorry @maratal — the commit hash is right but the linked issue is wrong, should be #1594. I've updated the commit message.

**Review by maratal — APPROVED** [review]
>These instructions were added in https://github.com/ably/ably-cocoa/commit/9a1e84cb10aace173bd43348b23ce75fdecf2f98, as part of the PR for adding
Swift Package Manager support

I don't agree (if I understood right), because https://github.com/ably/ably-cocoa/pull/1594 was only addressing https://github.com/ably/ably-cocoa/issues/1559. Which in its turn was an outcome of the PR for adding Swift Package Manager support. Since it's a minor commentary issue I'm approving nevertheless.

**Comment by lawrence-forooghian** [comment]
Ah yes, sorry! The first commit was meant to be 9691ebc. I've updated. Does that look right now?

**Comment by lawrence-forooghian** [comment]
@maratal pointed out that the commit message is still wrong — the mention of 9a1e84c should actually be 9691ebc. Unfortunately this is now merged so there's not loads that I can do, but leaving a message here in case somebody ends up on this PR in the future.

**Pull request merged**
