### PR TITLE
Try CI on macOS 13 explicitly.

### PR DESCRIPTION
**Pull request by maratal**
Not for merging

### CODE REVIEW

**Comment by maratal** [comment]
[This](https://github.com/ably/ably-cocoa/actions/runs/5248864696) run for iOS was made with the Nimble v11 (the commit unfortunately was lost because of force push), and failed tests are the same as in [tvOS run](https://github.com/ably/ably-cocoa/actions/runs/5371863599/jobs/9744902255) with the Nimble v9. So I guess it has something to do with the Xcode 14.3 and not Nimble.

**Comment by lawrence-forooghian** [comment]
I'll try running on Xcode 14.2 on macOS 13. But I'm a bit confused — if you've seen the same test failures on tvOS 16.4 then what makes you think it's a "macOS 13 thing"?

**Comment by lawrence-forooghian** [comment]
I ran the macOS tests on commit 01b0eb7990b0b48b1aac7fe07aa765e47e6ee67e, on macOS 13.4.1, with Xcode 14.2, and did not get any test failures.

**Comment by maratal** [comment]
> I'll try running on Xcode 14.2 on macOS 13. But I'm a bit confused — if you've seen the same test failures on tvOS 16.4 (which is what I understand from [#1760 (comment)](https://github.com/ably/ably-cocoa/pull/1760#issuecomment-1606290881)) then what makes you think it's a "macOS 13 thing"?

It's because that run under tvOS has an invalid setup - tvOS 16.4 on Xcode 14.2. Shouldn't be the case. So yeah, it's a Xcode 14.3 thing (including macOS 13 itself [run](https://github.com/ably/ably-cocoa/actions/runs/5248864703/jobs/9480944432))

**Comment by maratal** [comment]
[Another](https://github.com/ably/ably-cocoa/pull/1783) set of experiments finally showed that this depends only on whether it's on CI macOS 13. The same tests on [macOS](https://github.com/ably/ably-cocoa/actions/runs/5496549573), [iOS](https://github.com/ably/ably-cocoa/actions/runs/5496549577) and [tvOS](https://github.com/ably/ably-cocoa/actions/runs/5496549575) failed under macOS 13 and Xcode 14.2 (they are fine on Xcode 14.2 under macOS 12). [Here](https://github.com/ably/ably-cocoa/pull/1783) are the same failures under Xcode 14.3. Also [here](https://github.com/ably/ably-cocoa/actions/runs/5371863599/jobs/9744902255) the same failures on macOS 13 and Xcode 14.3 for tvOS, but with old Nimble (tvOS compiles in Xcode 14.3 without need to update Nimble for some reason). Those tests succeed locally on macOS 13 and Xcode 14.3. @lawrence-forooghian

**Comment by maratal** [comment]
This work is done in https://github.com/ably/ably-cocoa/pull/1801

**Pull request closed without merging**
