### PR TITLE
Replace Travis with GitHub workflow

### PR DESCRIPTION
**Pull request by QuintinWillison**

### CODE REVIEW

**Comment by QuintinWillison** [comment]
@ricardopereira I had a run at this but it's not quite there. I'm going to be able to pick this up again next week, but in the meantime please feel free to add some commits to this branch if you can see anything obvious we can fix to get these passing. I expect this is workflow and/or build environment related, rather than an issue with the test suite itself.

**Comment by ricardopereira** [comment]
Carthage now supports Xcode 12.0, the project should use XCFrameworks ([v0.37.0](https://github.com/Carthage/Carthage/releases/tag/0.37.0)).

> Building a framework using Xcode 12 fails with a build error from `xcrun lipo`. Fix by passing `--use-xcframeworks` and [re-integrating your dependencies as XCFrameworks](https://github.com/Carthage/Carthage#migrating-a-project-from-framework-bundles-to-xcframeworks).

> Carthage builds fat frameworks, which means that the framework contains binaries for all supported architectures. Until Apple Silicon was introduced it all worked just fine, but now there is a conflict as there are duplicate architectures (arm64 for devices and arm64 for simulator). This means that Carthage cannot link architecture specific frameworks to a single fat framework.

**Comment by ricardopereira** [comment]
The test suite will get better when #1092 lands the `main` branch.

**Comment by QuintinWillison** [comment]
Thanks, @ricardopereira - I've rebased https://github.com/ably/ably-cocoa/pull/1092 on the branch underlying this PR to validate that assertion.

**Comment by QuintinWillison** [comment]
Before I land this PR, I'm planning to:

- [ ] Take a closer look at the `restore-keys` arg added in https://github.com/ably/ably-cocoa/pull/1103/commits/1890c71de08a02bbbb46c75c6b55b17fb35629cd - it looks odd
- [ ] Remove the 3019 workaround script if it's no longer needed - references removed in https://github.com/ably/ably-cocoa/pull/1103/commits/e0be3d2c250a1b401e39254f128872b24d786068
- [ ] Understand why we've moved from `macos-latest` to `macos-10.15` - this feels wrong

**Comment by ricardopereira** [comment]
- About action/cache `restore-keys`: it is _an ordered list of keys to use for restoring the cache if no cache hit occurred for key_. More details at [Understanding Cache Action keys](https://github.community/t/understanding-cache-action-keys/17503). I implemented the cache action based on this blog post: [Caching dependencies in Github Actions](https://sarunw.com/posts/caching-dependencies-in-github-actions/).
 - Regarding the `macos-10.15`, I changed it to be more predictable the tools version that the workflow is using. As far as I understood, `macos-latest` is more volatile.

**Comment by QuintinWillison** [comment]
Taking a different tack for a bit. I've merged this pull request's underlying branch into the branch underlying #1092 ... if the checks look sensible there then I may land that pull request onto this one so I can work on the two together.

**Comment by QuintinWillison** [comment]
Whoop, a successful run of checks! 🎉 

@ricardopereira or @paddybyers, either of you happy to approve this PR, please?

**Comment by paddybyers** [comment]
Do you have any idea what the nature of the failures are that have required tests to be disabled?

**Comment by ricardopereira** [comment]
@paddybyers They fail intermittently like: test takes longer than expected, race conditions, unexpected answers from sandbox, etc.

**Comment by QuintinWillison** [comment]
@paddybyers for the tests that I've disabled, the majority are disabled for expectation failures that look like they relate to the client-side design of the test (i.e. race conditions) - e.g. lack of enough waits before testing expectations.

**Review by ricardopereira — APPROVED** [review]

**Review by paddybyers — APPROVED** [review]
Nice, but please also @ricardopereira give your comments

**Comment by ricardopereira** [comment]
Next step will be going through every disabled test and check what might be the issue and fix it.

**Pull request merged**
