### PR TITLE
Update AblyDeltaCodec to 1.3.2

### PR DESCRIPTION
**Pull request by ben-xD**

### CODE REVIEW

**Review by lukasz-szyszkowski — APPROVED** [review]

**Review by QuintinWillison — APPROVED** [review]
Does `Examples/SPM/Package.resolved` need updating too?

Also, perhaps revisit the title for this pull request - aligning with what you had on [this previous PR](https://github.com/ably/ably-cocoa/pull/1165), perhaps? (i.e. `DeltaCodecCocoa` > `AblyDeltaCodec`)

**Comment by lukasz-szyszkowski** [comment]
> Does `Examples/SPM/Package.resolved` need updating too?
> 
> Also, perhaps revisit the title for this pull request - aligning with what you had on [this previous PR](https://github.com/ably/ably-cocoa/pull/1165), perhaps? (i.e. `DeltaCodecCocoa` > `AblyDeltaCodec`)

IMO Package.resolved should be in .gitignore

**Review by maratal — APPROVED** [review]

**Comment by ben-xD** [comment]
> > Does `Examples/SPM/Package.resolved` need updating too?
> > Also, perhaps revisit the title for this pull request - aligning with what you had on [this previous PR](https://github.com/ably/ably-cocoa/pull/1165), perhaps? (i.e. `DeltaCodecCocoa` > `AblyDeltaCodec`)
> 
> IMO Package.resolved should be in .gitignore

I disagree. The lockfile is useful to ensure the the same versions of dependencies are used as recorded, as opposed to the latest dependency version available. For more information, take a look at https://forums.swift.org/t/package-resolved-should-go-in-the-gitignore/14699/12

**Comment by ben-xD** [comment]
> Does `Examples/SPM/Package.resolved` need updating too?

There's a bigger problem for that file, it references a local path on @lukasz-szyszkowski's computer

```
      {
        "package": "ably-cocoa",
        "repositoryURL": "/Users/lukaszszyszkowski/@projekty_ios/ably-cocoa",
        "state": {
          "branch": null,
          "revision": "23433617838d34ef8d963883b12c8a77f1a1b4bb",
          "version": null
        }
      },
```

**Comment by ben-xD** [comment]
> > Does `Examples/SPM/Package.resolved` need updating too?
> 
> There's a bigger problem for that file, it references a local path on @lukasz-szyszkowski's computer. Also, I don't think this example app runs outside of @lukasz-szyszkowski's computer, since it references a `env("PACKAGE_URL")`. Try to use a relative path, not an environment variable.
> 
> ```
>       {
>         "package": "ably-cocoa",
>         "repositoryURL": "/Users/lukaszszyszkowski/@projekty_ios/ably-cocoa",
>         "state": {
>           "branch": null,
>           "revision": "23433617838d34ef8d963883b12c8a77f1a1b4bb",
>           "version": null
>         }
>       },
> ```

This has been fixed in https://github.com/ably/ably-cocoa/pull/1218

**Pull request merged**
