### PR TITLE
Improve RTN4a test

### PR DESCRIPTION
**Pull request by ricardopereira**
The test is ok but it should also check for the previous state from the connection state change.

Related with #1085.

### CODE REVIEW

**Comment by ricardopereira** [comment]
@tiholic From the test, the lib is doing the right thing. Please, could share an example reproducing the `ConnectionStateChange#previous` being null? cc @QuintinWillison

**Comment by ricardopereira** [comment]
Screenshot 2020-11-05 at 10 55 27

**Comment by tiholic** [comment]
@ricardopereira I've noticed that lib is doing just fine. There has been a goof up at my end 🤦‍♂️  
Thanks

**Comment by ricardopereira** [comment]
Rebased with `main`.

**Comment by lukasz-szyszkowski** [comment]
Closing reason https://github.com/ably/ably-cocoa/issues/1085#issuecomment-724173679

**Pull request closed without merging**
