### PR TITLE
Update Example

### PR DESCRIPTION
**Pull request by ricardopereira**

### CODE REVIEW

**Comment by paddybyers** [comment]
So why are we using a fork of msgpack?

**Comment by ricardopereira** [comment]
@paddybyers Because the original msgpack is missing the macOS target so I forked it. I created a PR but the owner ignored it https://github.com/rvi/msgpack-objective-C/pull/5.

**Comment by ricardopereira** [comment]
Currently, this lib is using 3 forks:
 - [KSCrash](): crash/exceptions handler with our custom needs.
 - [SocketRocket](https://github.com/ably-forks/SocketRocket): removed warnings and added Carthage support.
 - [MsgPack](https://github.com/ably-forks/msgpack-objective-C): added macOS support.

**Comment by ricardopereira** [comment]
@paddybyers Are you clarified?

**Pull request merged**
