### PR TITLE
Nimble new xcode compatibility

### LINKED ISSUE #1768: Build fails compiling Nimble framework in Xcode 14.2
```
Global function 'allPass' requires the types 'URLRequest' and '((_) -> Bool).ValueType' be equivalent
```

### PR DESCRIPTION
**Pull request by maratal**
Closes #1768 

Review after https://github.com/ably/ably-cocoa/pull/1769

### CODE REVIEW

**Comment by maratal** [comment]
Looks like it's a macOS 12 issue then..

**Comment by maratal** [comment]
Initially creation of the #1768 was the result of erroneous local leftovers from Carthage folder with a newer version of Nimble (v11). Installing original version (v9) fixed this problem for Xcode 14.2.

But.

Xcode 14.3 requires installation of a newer version of Nimble (I've chosen v11 as [marked](https://github.com/Quick/Nimble/releases/tag/v11.2.2) as first compatible with Xcode 14.3) because of the warning compiler gives:

```
/Users/runner/work/ably-cocoa/ably-cocoa/Carthage/Checkouts/Nimble/Nimble.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.10, but the range of supported deployment target versions is 10.13 to 13.3.99. (in target 'Nimble-macOS' from project 'Nimble')
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/runner/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/Nimble/v9.2.1/Build/Intermediates.noindex/ArchiveIntermediates/Nimble-macOS/IntermediateBuildFilesPath/Nimble.build/Release/Nimble-macOS.build/Objects-normal/x86_64/DSL-463c5d0d2dc3dddff5eff23e4999c37c.o /Users/runner/work/ably-cocoa/ably-cocoa/Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/DSL.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Nimble-macOS' from project 'Nimble')
(1 failure)

/Users/runner/work/ably-cocoa/ably-cocoa/Carthage/Checkouts/Nimble/Nimble.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 9.0, but the range of supported deployment target versions is 11.0 to 16.4.99. (in target 'Nimble-iOS' from project 'Nimble')
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/runner/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3_14E222b/Nimble/v9.2.1/Build/Intermediates.noindex/ArchiveIntermediates/Nimble-iOS/IntermediateBuildFilesPath/Nimble.build/Release-iphoneos/Nimble-iOS.build/Objects-normal/arm64/DSL-463c5d0d2dc3dddff5eff23e4999c37c.o /Users/runner/work/ably-cocoa/ably-cocoa/Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/DSL.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'Nimble-iOS' from project 'Nimble')
(1 failure)
```

And since we have "warnings as errors" build setting, it fails the build process.

Might it be a chance that this setting was changed locally on your machine? (See [carthage-xcodebuild-logs](https://github.com/ably/ably-cocoa/actions/runs/5370800731?pr=1760) file with above warnings).

Installing a newer version of Nimble gives another set of errors, collected in this umbrella issue https://github.com/ably/ably-cocoa/issues/1764 @lawrence-forooghian

**Comment by maratal** [comment]
https://github.com/ably/ably-cocoa/pull/1760#issuecomment-1606290881

**Comment by lawrence-forooghian** [comment]
@maratal yeah, I'm able to reproduce locally (i.e. running `make update_carthage_dependencies_macos` is failing for me). I think that the warning that you've mentioned above is not the cause of the failure though — it's an error in `DSL.m` that's being emitted further above:

```
/Users/runner/work/ably-cocoa/ably-cocoa/Carthage/Checkouts/Nimble/Sources/NimbleObjectiveC/DSL.m:71:41: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
NIMBLE_EXPORT NMBPredicate *NMB_beTruthy() {
                                        ^
                                         void
```

But yeah, you're right that we need to fix it in Xcode 14.3.

**Pull request closed without merging**
