### PR TITLE
Remove SAMKeychain dependency and use internal solution

### PR DESCRIPTION
**Pull request by ricardopereira**
SAMKeychain has been archived and not maintained anymore #897.

### CODE REVIEW

**Comment by QuintinWillison** [comment]
Relates to #949

**Comment by mikepulaski** [comment]
This is great! I'm actually in the middle of migrating dependencies for [Tuple](https://tuple.app) right now and these changes would be super handy.

Looking forward to getting this downstream 👍

**Comment by QuintinWillison** [comment]
Hmm, some to unpick here. I hoped this would be simple but @ricardopereira had forked from his Travis PR which is still in Draft. I'm going to push some commits to remove those conflations for now as I believe the SAMKeychain removal piece is pretty self-contained.

**Comment by QuintinWillison** [comment]
That's better. Essence restored.

Sorry for the noise, @paddybyers and @tcard, but all good for review now. 😁

**Review by paddybyers — APPROVED** [review]
LGTM in principle, but I've not reviewed the code in detail.

**Review by QuintinWillison — APPROVED** [review]

**Review by tcard — COMMENTED** [review]
Sorry I'm late. I'm not really familiar with the involved APIs, but assuming their usage is correct, LGTM.

**Pull request merged**
