### PR TITLE
Integrate `Aspects` dependency with project codebase

### PR DESCRIPTION
**Pull request by l-szyszkowski**
Aspects dependency is 9yrs old code and it won't compile with Xcode 14.3 because of it's low deployment target config.
We could fork this repo and change configuration, but this is just one file (and header) so I decided to integrate it into project codebase.

### CODE REVIEW

**Review by lawrence-forooghian — CHANGES_REQUESTED** [review]
Is this PR meant to have 11 commits? It seems like it contains the contents of #1685.

Also, there still seem to be references to `Aspects.xcframework` in the project and references to `Aspects` in the Carthage files.

**Comment by l-szyszkowski** [comment]
> Is this PR meant to have 11 commits? It seems like it contains the contents of #1685.

Thanks for pointing this out. It's fixed now.

> Also, there still seem to be references to `Aspects.xcframework` in the project and references to `Aspects` in the Carthage files.

changed here d8944a28a773ffab1d74936475dfb0d44c46d228

**Comment by lawrence-forooghian** [comment]
@lukasz-szyszkowski I've put this back into draft since CI is failing. Please could you re-open once CI is passing? Thanks 🙂

**Comment by lawrence-forooghian** [comment]
@lukasz-szyszkowski does this resolve #1686? If so, please can you mark it as doing so, so that when this is merged that issue gets closed?

**Comment by l-szyszkowski** [comment]
> @lukasz-szyszkowski does this resolve #1686? If so, please can you mark it as doing so, so that when this is merged that issue gets closed?

I'm not sure what you meant 😅 you've linked this PR in your comment. Did you mean this issue https://github.com/ably/ably-cocoa/issues/1667?

**Comment by lawrence-forooghian** [comment]
> Did you mean this issue #1667? 

🤦 I did!

> If yes, I've already linked it.

Thank you 🙂

**Review by lawrence-forooghian — APPROVED** [review]

**Pull request merged**
