### PR TITLE
Compile SocketRocket directly into the SDK

### PR DESCRIPTION
**Pull request by lawrence-forooghian**
# What’s new

This removes SocketRocket as a dependency from the `Cartfile` and podspec, and compiles SocketRocket directly into the SDK. It uses a submodule to pull the SocketRocket code in.

We're doing this as part of a wider effort to reduce the number of transitive dependencies that we impose on users of the SDK. See #949 for more details.

The commit messages explain what I’ve done in lot more detail, and I'd recommend reviewing this commit-by-commit.

# Questions for reviewers

I've done a fair bit of testing myself - mainly to check that the Carthage and CocoaPods builds are compiling correctly, and that the LICENCE is correctly included in the zip file that we generate for upload to GitHub. However, I'm not too sure how to test that everything is working functionally. I have a handful of test failures when running the unit tests, but my understanding is that this is to be expected as we do have some intermittent failures. What can we do to increase our confidence in merging these changes?

### CODE REVIEW

**Review by ricardopereira — APPROVED** [review]
🙌 Noice! So with this we can use websocket using URLSession in iOS 13+ and maintain SocketRocket for older versions, right?

**Comment by lawrence-forooghian** [comment]
Yep, we could certainly do that if we wanted to, but that would be a future enhancement. This piece of work is just to hide the SocketRocket dependency from consumers of the SDK.

**Comment by QuintinWillison** [comment]
I had a quick run at making this pull request viable as it had been left to languish for far too long, however it's not immediately obvious to me why the build would be failing now (in something seemingly unrelated).

**Review by QuintinWillison — CHANGES_REQUESTED** [review]
Thanks for removing the superfluous files, @maratal. 👍 

However (and apologies for only just noticing this) but can you please remove the unnecessary layer of folder indirection for socket rocket. From root I would expect to be seeing source files at `SocketRocket/` rather than `SocketRocket/SocketRocket/` as is currently the case.

**Comment by maratal** [comment]
> Thanks for removing the superfluous files, @maratal. 👍
> 
> However (and apologies for only just noticing this) but can you please remove the unnecessary layer of folder indirection for socket rocket. From root I would expect to be seeing source files at `SocketRocket/` rather than `SocketRocket/SocketRocket/` as is currently the case.

It was done not to face possible “include” issues since the whole thing is to be replaced soon. The less we touch it, the better. But probably I shouldn’t cut corner there… 🤪

**Comment by QuintinWillison** [comment]
Oh, I see. That's a fair point, @maratal.

Also, we need to get checks passing. FYI, @lukasz-szyszkowski

**Review by QuintinWillison — APPROVED** [review]

**Review by lukasz-szyszkowski — APPROVED** [review]
LGTM, but we have to be sure that everything works fine ... so, all tests have to be "green." 🤷‍♂️

**Comment by maratal** [comment]
Since this is a small subset of what @lukasz-szyszkowski has done in https://github.com/ably/ably-cocoa/pull/1136
(and directly included in it via commit https://github.com/ably/ably-cocoa/pull/1136/commits/a4c4aa97e5d917c789c8ca4e6b4a88bab1e13606)
I would prefer to just close this PR bc time cost of trying to merge it with main is too high and thus makes no sense.

**Comment by lukasz-szyszkowski** [comment]
> Since this is a small subset of what @lukasz-szyszkowski has done in #1136
> (and directly included in it via commit [a4c4aa9](https://github.com/ably/ably-cocoa/commit/a4c4aa97e5d917c789c8ca4e6b4a88bab1e13606))
> I would prefer to just close this PR bc time cost of trying to merge it with main is too high and thus makes no sense.

I'm closing this one, changes are in #1136

**Pull request closed without merging**
