### PR TITLE
Turned off newly added clang flag

### LINKED ISSUE #1076: Enable CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER for project, if possible
On updating the project to Xcode 12's recommended settings it suggested enabling this build flag.

But when I enable it we get lots of warnings. It appears to be highlighting issues in private headers, which I find a bit confusing, but I don't have time to investigate now so creating this issue to look later.

Screenshot 2020-10-07 at 13 25 01

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-364) by [Unito](https://www.unito.io)

### PR DESCRIPTION
**Pull request by maratal**
Closes #1076 ?

Adding and turning off this flag helps to get rid of warnings

https://stackoverflow.com/a/63989790/961037

### CODE REVIEW

**Review by lukasz-szyszkowski — APPROVED** [review]

**Comment by lawrence-forooghian** [comment]
Hey @maratal, do you think you could explain a little more about why you think we should disable this warning? Warnings are, in general, a good thing. Is there a reason we can't fix the code that is triggering these warnings?

**Comment by maratal** [comment]
> Hey @maratal, do you think you could explain a little more about why you think we should disable this warning? Warnings are, in general, a good thing. Is there a reason we can't fix the code that is triggering these warnings?

In my opinion it's confusing, it wants all quoted headers replaced with angle brackets which has no sense to me. If we ever decide to do that, we can always turn on this flag back. But until then it's useless. Also seems nobody in the community has any clue why it behaves like that. Everybody just turned it off. More info here
https://github.com/CocoaPods/CocoaPods/issues/9902 and here
https://stackoverflow.com/questions/63646607/xcode-12-using-firebase-pods-lexical-or-preprocessor-issue-pb-h-file-not-fou/63648164#63648164

**Comment by lawrence-forooghian** [comment]
Where are you seeing these warnings? I'm not seeing any when I build the project in Xcode 13.1. Does it occur for you on a fresh checkout of the project?

**Comment by maratal** [comment]
@lawrence-forooghian 

Screenshot 2021-11-15 at 15 34 30

**Review by lawrence-forooghian — APPROVED** [review]

**Pull request merged**
