### PR TITLE
Fix/694 static analyser issues

### PR DESCRIPTION
**Pull request by maratal**
Fixed the most obvious static analyser issues

### CODE REVIEW

**Comment by lawrence-forooghian** [comment]
Hey @maratal – it looks like you're still working on this one (new commits pushed yesterday). Perhaps it would be best to mark it as a draft so that we know when it's ready for review? Because I see that @lukasz-szyszkowski has already approved it, but it's changed since he approved it.

**Comment by lawrence-forooghian** [comment]
I'm also curious where in Xcode you're seeing these static analyser warnings?

**Comment by maratal** [comment]
> Perhaps it would be best to convert it to a draft so that we know when it's truly ready for review?
It certainly would, but I've finished already =) Now it's ready.

> I'm also curious where in Xcode you're seeing these static analyser warnings?
Menu->Product->Analyze

**Review by QuintinWillison — COMMENTED** [review]
As discussed in yesterday's in-person call, I would like to see evidence that this is being (or will be) checked in the CI environment (GitHub workflows). I believe that would be one of two options:

1. Add to this PR a commit that switches on static analyzer when building (`RUN_CLANG_STATIC_ANALYZER` build setting, I think) - or, perhaps, run `xcodebuild analyze` from workflow(s)
2. Create an issue to add this to our backlog - recognising that when we work on that there may be additional transgressions to fix

**Review by lawrence-forooghian — APPROVED** [review]
Looks good – I agree with what @QuintinWillison said about getting this done in CI, too.

**Comment by maratal** [comment]
I agree too, but I think it should be done in a separate issue. Will do.

**Review by QuintinWillison — APPROVED** [review]

**Pull request merged**
