### PR TITLE
[PREVIEW] Swift Package Manager support

### PR DESCRIPTION
**Pull request by lukasz-szyszkowski**
Closes https://github.com/ably/ably-cocoa/issues/819

### CODE REVIEW

**Comment by ben-xD** [comment]
I also noticed some warnings and errors in Xcode related to `ably-cocoa`:
CleanShot 2021-06-11 at 12 28 50

CleanShot 2021-06-11 at 12 33 44


---

Less important (since many libs don't bother with instructions because SPM is quite easy to use), but can we add usage to README?

- Add package dependency as `.package(url: "https://github.com/ably/ably-cocoa", from: "1.2.4")` (but this version might be wrong, need to wait for release i guess)
- Add target dependency to your target: `.product(name: "Ably", package: "ably-cocoa"),`
- In an example app (in the future), it would be clearer.

**Comment by lukasz-szyszkowski** [comment]
I know about msgpack version, I guess it's a task for @ricardopereira or we could bump our min version for macOS

**Comment by ben-xD** [comment]
Is it possible to delete those `Info.plist` files? i dont know why _libraries_ need it.

**Comment by ben-xD** [comment]
Now I'm just trying to compile a target, and source line being compiled `import Ably` is throwing an error: `No such module 'Ably'`

**Comment by lukasz-szyszkowski** [comment]
> Is it possible to delete those `Info.plist` files? i dont know why _libraries_ need it.
me neither

**Comment by lukasz-szyszkowski** [comment]
> Now I'm just trying to compile a target, and source line being compiled `import Ably` is throwing an error: `No such module 'Ably'`

how did you deal with wrong version of `msgpack` ?

**Comment by ben-xD** [comment]
@lukasz-szyszkowski, I know this is labelled as `WIP`, but just wanted to double check if you're aware that the current project doesn't build (at least for me). The `ably-asset-tracking-cocoa` (an SDK which depends on ably-cocoa) also has the same error. I think it would be great if you can test using Ably inside another Xcode project (to emulate customers using this SDK). I'm using in a Swift package though.

**Comment by lukasz-szyszkowski** [comment]
more here https://github.com/ably/ably-cocoa/pull/1136

**Pull request closed without merging**
